sudo: false
language: node_js
node_js:
  - "8"
install:
  npm install
script:
  - npm test -- --coverage # Include coverage when running tests
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
